name: "👉 Deploy to GitHub Pages"

on:
  push:
    branches:
      - master

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://github.com/Vladimir-Urik/games-frontend.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}